Fix issue #1016 Authenticated users can go to the pages that are for Non Authenticated user
DemocracyLab/CivicTechExchange pull request #1020
Opened 2023-08-20 20:28 UTC by QuanGiap

2023-08-20 23:50 UTC, AM-77 commented
@QuanGiap thank you for the PR.

just a suggestion, I think the url access restriction to /login and /signup when the user is already logged in should happen on the backend instead of the frontend, that way we dont even allow the user to load the page at all.

2023-08-21 17:31 UTC, QuanGiap commented
> @QuanGiap thank you for the PR.
> 
> just a suggestion, I think the access restriction to /login and /signup when the user is already logged in should happen on the backend instead of the frontend, that way we dont even allow the user to load the page at all.

2023-08-21 17:31 UTC, closed without merging

2023-08-21 19:19 UTC, QuanGiap commented
> @QuanGiap thank you for the PR.
> 
> just a suggestion, I think the access restriction to /login and /signup when the user is already logged in should happen on the backend instead of the frontend, that way we dont even allow the user to load the page at all.

That is a good suggestion, but it can bypass the check if the front end uses urlHelper.navigateToSection(). It uses history.pushState() which causes the browser won't attempt to load the given URL.

2023-10-22 01:24 UTC, marlonkeating requested changes

2023-10-22 01:24 UTC, marlonkeating commented on common/components/controllers/LogInController.jsx
> +    }
Let's make this its own function in [url.js](https://github.com/DemocracyLab/CivicTechExchange/blob/2a53c9645944133f6964cde357eed18d309b1f74/common/components/utils/url.js#L70)

2023-10-24 00:57 UTC, marlonkeating requested changes
Refactor looks good, but would be good to add a unit test for the helper method at https://github.com/DemocracyLab/CivicTechExchange/blob/024bd76b3b526b2f94c620f08315caff3081c5af/common/components/test/utils.test.js#L98