Impact Dashboard - Cmu Practicum 23
DemocracyLab/CivicTechExchange pull request #1075
Opened 2023-11-20 04:01 UTC by SebZhuC

2023-11-21 17:49 UTC, marlonkeating commented on civictechprojects/views.py
> +    volunteers = VolunteerRelation.objects.filter(is_approved=True)
```suggestion
    volunteers = VolunteerRelation.objects.filter(is_approved=True, deleted=False)
```

2024-01-11 02:05 UTC, marlonkeating requested changes

2024-01-11 02:05 UTC, marlonkeating commented on common/components/controllers/AggregatedDashboardController.jsx
> +    document.getElementById('detailButton').style.display = 'none';
TODO: Inline style instead

2024-01-11 02:05 UTC, marlonkeating commented on example.env
Why is this being deleted?

2024-01-11 02:05 UTC, marlonkeating commented on oauth2/apps.py
> -
Extraneous space

2024-01-28 21:27 UTC, marlonkeating requested changes

2024-01-28 21:27 UTC, marlonkeating commented on common/components/controllers/AggregatedDashboardController.jsx
There are serious performance issues with this page as it stands.  Multiple components have their own separate API calls, which on aggregate result in a long, fragmented page load where individual charts load at different times.  For the sake of performance, I recommend putting all the data behind a single API call (whose payload should be cached since the data does not change often).

2024-02-02 01:23 UTC, typesend commented on common/components/controllers/AggregatedDashboardController.jsx
Resolved in #1088

2024-02-02 01:25 UTC, typesend commented
Closing this PR as it lives on as #1088

2024-02-02 01:25 UTC, closed without merging