Update participant count
DemocracyLab/CivicTechExchange pull request #1097
Opened 2024-03-07 06:13 UTC by andrewindechemain

This pull request:
-Removes participant count and glyph from the join conference button

2024-03-22 01:49 UTC, marlonkeating requested changes

2024-03-22 01:49 UTC, marlonkeating commented on common/components/common/event_projects/JoinConferenceButton.jsx
> -          </span>
This looks like the only applicable change related to this feature.  Is there something I'm missing with the other changes?

2024-03-25 16:58 UTC, marlonkeating requested changes

2024-03-25 16:58 UTC, marlonkeating commented on common/components/componentsBySection/CreateEvent/EventPreviewForm.jsx
> +        <AboutEventDisplay event={this.props.main_footer} viewOnly={true}/>
Why is this change here?

2024-03-25 16:58 UTC, marlonkeating commented on civictechprojects/static/css/partials/_AllowMarkdown.scss
> +}
Unneeded change

2024-03-25 16:58 UTC, marlonkeating commented on civictechprojects/static/css/styles.scss
> +@import "partials/RecentProjects";
Unneeded change

2024-03-28 16:52 UTC, marlonkeating requested changes
To make a clean PR and omit unnecessary commits, I would either make a new branch based off the latest master branch, or do `git rebase master`

2024-03-28 17:12 UTC, andrewindechemain commented
> To make a clean PR and omit unnecessary commits, I would either make a new branch based off the latest master branch, or do `git rebase master`

Hi Marlon,I have opened a new branch.The rebase is up to date with Master. The link is : https://github.com/DemocracyLab/CivicTechExchange/tree/Update_ParticipantCount

2024-03-29 07:05 UTC, closed without merging