Allow inline editing of user profile
DemocracyLab/CivicTechExchange pull request #683
Opened 2021-07-07 18:46 UTC by marlonkeating

2021-07-17 05:08 UTC, PeterBreen requested changes
Functionally it works fine, but there's some polish I think it needs before we launch it. Most of these should be fairly quick to fix. If you want me to take a deeper dive into the profile's look and feel for polish I can do that once we knock these out.

2021-07-17 05:08 UTC, PeterBreen commented on common/components/controllers/AboutUserController.jsx
> +              <h2 className="text-uppercase">Files</h2>
No other header on this page uses `text-uppercase` anymore, so let's remove it from here.

2021-07-17 18:54 UTC, marlonkeating commented on common/components/controllers/AboutUserController.jsx
>          {showEdit && this._renderEditUserButton()}
Button has been removed, and header link now points to profile page instead of edit page.

2021-07-19 20:25 UTC, marlonkeating commented on common/components/controllers/AboutUserController.jsx
> +          {this._renderEditControl("showEditBioModal")}
There is another field planned under About Me called 'Motivation', and my thinking was to wrap both of these into the modal.

2021-07-19 20:26 UTC, marlonkeating commented on common/components/controllers/AboutUserController.jsx
> +          {this._renderEditControl("showEditTagsModal")}
Similarly, we're planning new fields, Causes and Skills, that will live under Areas of Interest.

2021-07-19 21:39 UTC, marlonkeating commented on common/components/controllers/AboutUserController.jsx
>          <hr />
It was called for in the spec, but for now I agree it doesn't seem visually consistent.

2021-07-26 19:47 UTC, PeterBreen commented
Made a few changes, like we discussed in standup:
 - moved Bio edit icon next to biography section
 - moved Technologies edit icon next to technologies section
 
And then one we didn't, where the profile image was pushing the edit icon out of alignment/outside the column incorrectly. If you look at it now, the edit icons for profile image, name, and links are all vertically aligned as they should be.

2021-07-26 20:09 UTC, PeterBreen approved these changes

2021-07-28 22:24 UTC, merged