Unit test for guard.js.
DemocracyLab/CivicTechExchange pull request #701
Opened 2021-07-21 16:50 UTC by zh-zhang916

As the title says.

close #631

2021-07-28 21:58 UTC, marlonkeating requested changes
The current test is only testing the implementation details, where we want to test the behavior regardless if the implementation changes in the future.

2021-07-28 21:58 UTC, marlonkeating commented on common/components/test/utils.test.js
> +    expect(_.debounce).toBeCalledWith(testFunc, 1000, {leading: true});
I would instead test that testFunc was called only once after multiple invocations of Guard.duplicateInput's return function.

2021-08-04 17:39 UTC, marlonkeating requested changes
Test looks good so far.  There's a couple more things we should test

## Checklist ##
- [x] Verify return value of function is duplicated
- [ ] Verify function is called again after timeout period elapses

2021-08-04 18:20 UTC, zh-zhang916 commented
Fixed.

2021-08-11 18:18 UTC, marlonkeating approved these changes

2021-08-11 18:18 UTC, merged