Added the logic to redirect to previous page when user signs in from …
DemocracyLab/CivicTechExchange pull request #741
Opened 2021-08-26 23:02 UTC by pravalikarouthu

Redirecting to the page from which they clicked the Login button using OAuth source.

https://github.com/DemocracyLab/CivicTechExchange/issues/592

2021-08-31 21:05 UTC, marlonkeating requested changes
Good job, the fix seems to work well!  There's just a few code cleanliness items to address.  

If you can, also run [Flow ](https://flow.org/) on your javascript, which is something we're trying to use as a team.

2021-08-31 21:05 UTC, marlonkeating commented on common/components/common/integrations/SocialMediaSignupSection.jsx
>              </div>
The only difference between the link elements in this conditional is the url.  I would set the url in a separate variable above the return statement.

Also, you can simplify constructing the url arguments with
https://github.com/DemocracyLab/CivicTechExchange/blob/52e3996e3c71941f2eb0f7d628ba285b512bc3ec/common/components/utils/url.js#L256

2021-09-03 00:47 UTC, marlonkeating requested changes
I'm seeing some irregular spacing in the javascript code, which running [Flow](https://flow.org/) should solve automatically.

2021-09-03 00:47 UTC, marlonkeating commented on common/components/common/integrations/SocialMediaSignupSection.jsx
> +          }
This logic can be compressed using helper functions.
```suggestion
	  const args: Dictionary<string> = {prevPage: this.state.prevPage};
	  if(this.state.prevPageArgs) {
	    args["prevPageArgs"] = this.state.prevPageArgs;
	  }
	  const url: string =  "/api/login/" + app + urlHelper.argsString(args);
```

2021-09-08 17:21 UTC, pravalikarouthu commented on common/components/common/integrations/SocialMediaSignupSection.jsx
> +
Verified these changes to be working locally and hence committed it.

2021-09-08 23:22 UTC, marlonkeating approved these changes

2021-09-08 23:22 UTC, merged