Complete user and project endpoints
DemocracyLab/CivicTechExchange pull request #765
Opened 2021-09-22 18:56 UTC by justBanks

2021-11-15 12:41 UTC, justBanks commented
I have some things to discuss, as well as some super secret settings to share

2021-11-15 21:38 UTC, marlonkeating requested changes

2021-11-16 18:21 UTC, marlonkeating requested changes

2021-11-16 18:21 UTC, marlonkeating commented on salesforce/campaign.py
> +    stage_tags = list(project.project_stage.all().values())
In order to retrieve a Tag's display name from its slug, first retrieve the Tag object with
https://github.com/DemocracyLab/CivicTechExchange/blob/7a6588ae5417b655e58a448ff023b3523d418345/common/models/tags.py#L23

Once you have the Tag object, you can access the Tag's display name with
https://github.com/DemocracyLab/CivicTechExchange/blob/7a6588ae5417b655e58a448ff023b3523d418345/common/models/tags.py#L7

2021-12-16 01:25 UTC, marlonkeating requested changes

2021-12-16 02:03 UTC, justBanks commented on salesforce/client.py
> +                    response = self.__session.send(prepped_request)
We're about to send a prepped_request so it needs the auth header to be set.  The response just came back unauthorized, so authorize() was called in the next step; that is where the client's bearer_token is set, and hopefully that will persist in the static class variable.

Don't want to hit that unauthorized branch more than once, of course. The auth header is also set in initialize_session, where I expect subsequent instances to pull the token from the client's persisted value.

2021-12-16 02:05 UTC, justBanks commented on salesforce/campaign.py
> +                "type": "Informal (No Legal Entity Established)",
Right you are... I must have been avoiding dealing with tags at the time

2021-12-16 02:06 UTC, justBanks commented on docker-compose.yml
> -    env_file:
It's not a duplicate? I had things running fine without it

2021-12-16 09:17 UTC, justBanks commented on salesforce/campaign.py
> +                "type": "Informal (No Legal Entity Established)",
pushed the fix for this

2022-01-05 16:52 UTC, marlonkeating approved these changes

2022-01-05 16:53 UTC, merged