news
DemocracyLab/CivicTechExchange pull request #771
Opened 2021-09-29 20:13 UTC by zh-zhang916

2021-09-29 20:16 UTC, zh-zhang916 commented
As the title says.

close #746

2021-09-29 23:36 UTC, marlonkeating requested changes
I'm getting an error when trying to navigate to the news page with your changes.

![image](https://user-images.githubusercontent.com/322346/135362674-609ee328-af2e-4577-9727-07c87d17a710.png)

2021-09-29 23:36 UTC, marlonkeating commented on common/helpers/front_end.py
> +        return settings.BLOG_URL
We don't want to put in special cases like this, otherwise if we need to do more external redirects in the future things will become quite messy.

2021-09-30 22:37 UTC, marlonkeating approved these changes

2021-09-30 22:37 UTC, merged