Fontawesomeupgrade
DemocracyLab/CivicTechExchange pull request #864
Opened 2022-03-25 13:46 UTC by AndrewIndeche

2022-04-25 20:42 UTC, marlonkeating requested changes

2022-04-25 20:42 UTC, marlonkeating commented on common/components/constants/LinkConstants.js
> +  },
The only difference between this and the change at line 30 is capitalization, which should be covered by the "i" flag.

2022-04-25 20:42 UTC, marlonkeating commented on common/components/constants/LinkConstants.js
> +  Figma: "link_facebook",
You don't need to add an entry here.  It's covered under the DESIGN type.

2022-04-25 20:42 UTC, marlonkeating commented on common/components/constants/LinkConstants.js
> +    ],
Again, don't need this, it lives under DESIGN

2022-04-25 20:42 UTC, marlonkeating commented on common/components/utils/glyphs.js
> +  Figma: "fab fa-figma", // https://fontawesome.com/icons/figma?s=brands
Duplicate of line 8

2022-04-25 20:42 UTC, marlonkeating commented on docker-compose.yml
> +      - "5438:5438"
Why did you need to change this?

2022-04-25 23:58 UTC, marlonkeating requested changes
Currently the package.json imports aren't being used, we're still using the old import in 
https://github.com/DemocracyLab/CivicTechExchange/blob/fc545a165088113ac6d97ceb4da4ddaa00dd610c/civictechprojects/templates/new_index.html#L21

If you try putting a figma link in a project, you'll see that no icon shows up.

2022-05-26 19:00 UTC, marlonkeating requested changes
It seems to work fine, but in the change we've got v5.12.1 linked in new_index.html, and v.6.1.1 linked to in package.json.  If we really do need both, their versions should match up.

2022-05-26 20:16 UTC, AndrewIndeche commented on common/components/chrome/SocialFooter.jsx
> +        </div>
The spacing is only reflecting when versioning,i can't see and spacing locally

2022-05-26 23:02 UTC, marlonkeating requested changes
Looks good.  Go ahead and remove the yarn.lock changes now that package.json is no longer being changed.

2022-05-27 06:08 UTC, AndrewIndeche commented
> Looks good. Go ahead and remove the yarn.lock changes now that package.json is no longer being changed.

completed

2022-05-27 18:32 UTC, marlonkeating approved these changes

2022-05-27 18:32 UTC, merged