Companies section reordering and content updates
DemocracyLab/CivicTechExchange pull request #894
Opened 2022-07-30 23:30 UTC by schaferyan

Made the following changes to Companies Page, requested in issue #888 
- Moved Testimonials Carousel above Contact Form in both Hackathon and Sponsorship tabs
- Updated blog link in Hackathon tab
- Updated Prospectus links
- Updated Section background colors

closes #888

2022-08-01 17:52 UTC, PeterBreen commented on common/components/controllers/CorporateHackathonController.jsx
> +        <div className="corporate-hackathon-saying col-12 corporate-bg-light">
Did you mean to remove corporate-bg-light here or just reorder the class declarations?

2022-08-01 18:01 UTC, PeterBreen commented on common/components/controllers/CorporateHackathonController.jsx
> +            {/* TODO find where {window.BLOG_URL} is declared */}
Let's remove this and I'll write an issue that we need to document environment variables better in our Contributor's Guide. I reviewed it this morning and agree that we need a section about how to use them, not just how to load them.

2022-08-01 18:06 UTC, PeterBreen requested changes
I took a look and this looks good with one exception - but the section changes, content updates, and blog modifications all look excellent. 

However the section background for the carousel section still shows as white; to properly alternate it should be grey. If you remove the `corporate-bg-light` class from the controller (see the line comments I made) that ought to expose the background issues remaining.  My example screenshots may have been unclear, please let me know if you want me to annotate those better or something.

2022-08-01 18:07 UTC, PeterBreen commented on common/components/controllers/CorporateHackathonController.jsx
>          <div className="corporate-sponsorship-saying corporate-bg-light col-12">
This is an instance of `corporate-bg-light` to remove for the section background issue.

2022-08-01 18:25 UTC, schaferyan commented
Hey Peter it looks like my latest changes weren't pushed to the feature branch. I had removed the TODO comment and resolved the background shading. I'll fix this as soon as I have a moment, apologies for that mistake.

2022-08-01 18:41 UTC, PeterBreen commented on common/components/controllers/CorporateHackathonController.jsx
> +            {/* TODO find where {window.BLOG_URL} is declared */}
I created issue #895 for this one. If there's any specifics you want to make sure we include in the documentation, please comment on it there.

2022-08-04 00:02 UTC, PeterBreen requested changes
One tiny thing left (see suggested change) and it looks great on both mobile and desktop in my testing. 👍

2022-08-04 00:02 UTC, PeterBreen commented on common/components/controllers/CorporateHackathonController.jsx
> +:ww// democracylab.org/companies page --- TODO: rename controller
```suggestion
// democracylab.org/companies page --- TODO: rename controller
```
tiny clean-up item; removing this errant comment clears a build error.

2022-08-04 05:32 UTC, PeterBreen approved these changes

2022-08-05 17:23 UTC, merged