Xuanying #957 disable carousel auto advance
DemocracyLab/CivicTechExchange pull request #962
Opened 2023-04-11 00:42 UTC by SleeplessRegina

Disable carousel auto advance, make the carousel only support manually advance both in TestimonialCarousel and BlogCarousel.
Set the custom intervals to null and remove interval from our type statement.

2023-04-12 21:04 UTC, PeterBreen requested changes
It looks good, but please see the three line comments on instances of using interval as a prop that we may not need. But please do let me know if it is necessary :)

2023-04-12 21:04 UTC, PeterBreen commented on common/components/controllers/CorporateHackathonController.jsx
> +              interval={null}
Do we need to use interval={null} here, as well as in the TestimonialCarousel component itself? Carousel shouldn't be taking any props so I'm hoping it's safe to remove, but please test and let me know?

2023-04-12 21:04 UTC, PeterBreen commented on common/components/controllers/CorporateHackathonController.jsx
> +              interval={null}
Same question as above

2023-04-12 21:04 UTC, PeterBreen commented on common/components/controllers/LandingController.jsx
> +        <TestimonialCarousel interval={null} />
Same question as above

2023-04-13 00:05 UTC, SleeplessRegina commented
> It looks good, but please see the three line comments on instances of using interval as a prop that we may not need. But please do let me know if it is necessary :)

Yes, I removed the interval props of TestimonialCarousel then tested again and found it still looks good. Both the carousel won't automatically advance.

2023-04-23 00:19 UTC, PeterBreen approved these changes
Thanks for those changes; looks good, works exactly as expected 👍

2023-04-23 04:43 UTC, merged